### ISSUE TITLE
dump command does not support multiple databases

### ISSUE THREAD

**Issue by kajatiger** [makandra/geordi#101]
Rails allows [multiple databases](https://edgeguides.rubyonrails.org/active_record_multiple_databases.html) since the last version.
The database.yml with multiple databases has multiple database keys per environment, eg:
```
staging:
  primary:
    <<: *defaults
    database: some_staging_db
  reporting:
    <<: *defaults
    database: some_reporting_db
    migrations_paths: db/reporting_migrate
```
Since dumple only looks into the environment key and doesn't go one step further, it cannot find the adapter. Error message is:
```
Adapter " is not supported
```

I suppose we need to add that to the dumple script.
